### ISSUE TITLE
Data bag

### ISSUE THREAD

**Issue by mfonolleda** [Kgirthofer/lamp#1]
Hi!

First off thank you for writing this cookbook. I am trying to use it for my project but I get the following error:

"==> default: [2016-06-16T13:39:51+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/data/mysql/password"

I suspect the issue is with my databag. I have created a databag called mysql.json with the following contents:

{
 "password": "password"
 }

My chef solo config in Vagrant is as follows:

config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
    data_bags_path= "databags"  
    chef.add_recipe "lamp"  
end 

Any ideas what may be wrong?

Thanks in advance for your help.
- M

**Comment by Kgirthofer** [comment]
How are you creating your databag? It should be something like 
"knife data bag -z create name_of_data_bag data_id --secret-file encryption_token"
so to create the data bag for this use 
"knife data bag -z create mysql password --secret-file secret_file_here"
also your syntax is wrong for your data bag. You'll need to have it look like 
{
  "id": "password",
  "mysql_password": "whateverhtepasswordis"
}

When the cookbook calls #{sql_password['mysql_password']} it's looking into the var sql_password for a variable "mysql_password" - this is stored in the data bag item mysql with ID password as describe in sql_password = Chef::EncryptedDataBagItem.load('mysql', 'password') at the top of the recipe.

**Comment by mfonolleda** [comment]
I have created the data bag exactly as you mention but I am still getting the same error...

**Comment by Kgirthofer** [comment]
adjust your log level and see where it's looking for the data bag. what ever the issue is, it's caused by the data bag  not existing. Either a. you haven't created it in the right location, b. you haven't uploaded it to the right location, or c. you haven't named it with the above given syntax. Check your vagrant config to make sure it's pointing to the right location. 

Try "knife data bag list" to show your remote data bags, and knife data bag -z list to show local data bags. 
https://docs.chef.io/data_bags.html

**Comment by mfonolleda** [comment]
Thanks so much for your help Karl.

As you pointed out, originally my data bag was indeed incorrect. I solved
this thanks to your comments.

However, the problem is actually related to Vagrant.

https://github.com/chef/chef/issues/4948

Adding chef.version = "12.10.24" solves the issue.

Rgds,
- Miquel

On Thu, Jun 16, 2016 at 5:13 PM, Karl Girthofer notifications@github.com
wrote:

> adjust your log level and see where it's looking for the data bag. what
> ever the issue is, it's caused by the data bag not existing. Either a. you
> haven't created it in the right location, b. you haven't uploaded it to the
> right location, or c. you haven't named it with the above given syntax.
> Check your vagrant config to make sure it's pointing to the right location.
> 
> Try "knife data bag list" to show your remote data bags, and knife data
> bag -z list to show local data bags.
> https://docs.chef.io/data_bags.html
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Kgirthofer/lamp/issues/1#issuecomment-226516191, or mute
> the thread
> https://github.com/notifications/unsubscribe/ACLyJ-avpGRz15CimoxJ84pthJGIqzkrks5qMWgYgaJpZM4I3aGp
> .

## 

Miquel Fonolleda Ramboux
M +34 699 837-046
Parc Audiovisual de Catalunya
Carretera BV-1274 Km 1
08225 Terrassa (Barcelona)
www.albirasolutions.com

**Comment by daraul** [comment]
Forgive me, but I'm having this same problem and I don't know where/how to create the data bag.

Do I put it in the JSON field on the AWS console here? 

![image](https://user-images.githubusercontent.com/2440975/53695720-742c6a00-3d95-11e9-93fb-18b7d2325c78.png)

Or do I need to ssh into the instance and create it there?
